substitutions:
  _APP: 'task-cf'
  _PY_DIR: 'function'
  _TF_ACTION: 'apply'

steps:
  - id: 'where'
    name: 'gcr.io/cloud-builders/gcloud'
    args:
      - "auth"
      - "application-default"
      - "login"
#      - "auth application-default login"
#    script: |
#      !/usr/bin/env bash
#      gcloud
#      gcloud
#      ls -A
#      ls
#      pwd
#      echo "################"
#      export C=$(ls)
#      echo "################"
#      echo $C

#  - id: 'auth'
#    name: gcloud
#    args:
#      - "auth application-default login"

#  - id: 'pre-deployment-checks'
#    name: 'gcr.io/some-project/common-build'
#    dir: '${_PY_DIR}'
#    args:
#      - 'python3'
#      - '_DOCKER_TAG=3.8'
#      - '_LINT_OMIT_FILES=tests/*'
#    env:
#      - 'TF_ACTION=$_TF_ACTION'
#
#  - id: 'tf init'
#    name: 'gcr.io/task-cf-370913/terraform'
#    args:
#      - 'init'
#    env:
#      - 'PULL_REQUEST_ID=$_PR_NUMBER'
#      - 'BRANCH=$BRANCH_NAME'
#      - 'EXECUTOR=terraform'
#      - 'BACKEND_PREFIX=task-cf'
#
#  - id: 'tf plan'
#    name: 'gcr.io/task-cf-370913/terraform'
#    args:
#      - 'plan'
#    env:
#      - 'PULL_REQUEST_ID=$_PR_NUMBER'
#      - 'BRANCH=$BRANCH_NAME'
#      - 'EXECUTOR=terraform'
#      - 'BACKEND_PREFIX=task-cf'
#
#  - id: 'tf plan/apply'
#    name: 'gcr.io/task-cf-370913/terraform'
#    args:
#      - '${_TF_ACTION}'
#    env:
#      - 'PULL_REQUEST_ID=$_PR_NUMBER'
#      - 'BRANCH=$BRANCH_NAME'
#      - 'EXECUTOR=terraform'
#      - 'BACKEND_PREFIX=task-cf'

  - id: 'tf init'
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: sh
    args:
      - '-c'
      - 'terraform init -upgrade'

  - id: 'tf plan'
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: sh
    args:
      - '-c'
      - 'terraform plan -out=plan.out'

  - id: 'tf apply'
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: sh
    args:
      - '-c'
      - 'terraform apply plan.out'

options:
  substitution_option: 'ALLOW_LOOSE'
tags: ['service-${_APP}-${_TF_ACTION}']
