substitutions:
  _APP: 'task-cf'
  _PY_DIR: 'function'
  _TF_ACTION: 'apply'

steps:
#  - id: 'where'
#    name: 'ubuntu'
##    args: ['bash', '-c', 'echo "===================================================="']
#    script: |
#      #!/usr/bin/env bash
#      echo $_TF_DIR
#      ls -A
#      ls
#      pwd
#      echo "################"
#      export C=$(ls)
#      echo "################"
#      echo $C


#  - id: 'pre-deployment-checks'
#    name: 'gcr.io/some-project/common-build'
#    dir: '${_PY_DIR}'
#    args:
#      - 'python3'
#      - '_DOCKER_TAG=3.8'
#      - '_LINT_OMIT_FILES=tests/*'
#    env:
#      - 'TF_ACTION=$_TF_ACTION'
#
  - id: 'tf init'
    name: 'gcr.io/task-cf-370913/terraform'
    args:
      - 'init'
    env:
      - 'PULL_REQUEST_ID=$_PR_NUMBER'
      - 'BRANCH=$BRANCH_NAME'
      - 'EXECUTOR=terraform'
      - 'BACKEND_PREFIX=task-cf'

  - id: 'tf plan/apply'
    name: 'gcr.io/task-cf-370913/terraform'
    args:
      - '${_TF_ACTION}'
    env:
      - 'PULL_REQUEST_ID=$_PR_NUMBER'
      - 'BRANCH=$BRANCH_NAME'
      - 'EXECUTOR=terraform'
      - 'BACKEND_PREFIX=task-cf'

options:
  substitution_option: 'ALLOW_LOOSE'
tags: ['service-${_APP}-${_TF_ACTION}']
