steps:
  - id: "Activate virtual environment venv"
    name: 'hashicorp/dataflow-python3:latest'
    entrypoint: '/bin/bash'
    args: [ '-c', 'source /venv/bin/activate' ]
    waitFor: [ '-' ]

  - id: "Create dataflow template"
    name: 'hashicorp/dataflow-python3:latest'
    entrypoint: 'python'
    args: [ '-m', 'task_two.main',
            "--job_name=dataflow-job-task",
            "--project=task-cf-370913",
            "--region=US",
            "--template_location=gs://task-cf/template/test-job",
            "--staging_location=gs://task-cf/tmp/",
            "--temp_location=gs://task-cf/tmp/",
            "--runner=DataflowRunner",
            "--setup_file='task_two/setup.py'",
            "--autoscaling_algorithm=NONE"
    ]
    waitFor: [
      'Activate virtual environment venv'
    ]
